[project]
name="thedu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python=">=3.9"
dependencies = [
    "apsw>=3.50.4.0",
    "fastlite>=0.2.1",
    "sentence-transformers>=5.1.2",
    "uform>=3.1.3",
]

[dependency-groups]
dev = [
    "jupyterlab-quarto>=0.3.5",
    "nbdev>=2.4.6",
]
